spring:
  application:
    name: docuhelper-api
  kafka:
    producer:
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  ai:
    openai:
      chat:
        options:
          model: gpt-4.1-nano-2025-04-14
          stream-usage: true

graphql:
  packages:
    - "org.bmserver.app"
    - "org.bmserver.core"
    - "org.bmserver.gateway"

