server:
  port: ${PORT:8080}

spring:
  r2dbc:
    url: r2dbc:pool:postgres://${DB_HOST}:${DB_PORT}/docuhelper
    username: ${DB_USER:postgres}
    password: ${DB_PASSWD:password}
  security:
    jwt:
      secret: ${JWT_SECRET}
  kafka:
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}
    consumer:
      auto-offset-reset: earliest
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  ai:
    ollama:
      base-url: ${OLLAMA_ENDPOINT}
      embedding:
        model: ${OLLAMA_EMBEDDING_MODEL}
    openai:
      api-key: ${OPENAI_API_KEY}

docuhelper:
  file:
    endpoint: ${DOCUHELPER_FILE_ENDPOINT}

dev:
  default:
    login:
      enable: false