FROM openjdk:17-jdk-slim-buster
LABEL maintainer=docuhelper-api

ARG DB_HOST
ARG DB_PORT
ARG DB_USER
ARG DB_PASSWD
ARG JWT_SECRET
ARG KAFKA_HOST
ARG KAFKA_PORT
ARG DOCUHELPER_FILE_ENDPOINT
ARG OPENAI_API_KEY
ARG ELASTICSEARCH_HOST
ARG ELASTICSEARCH_PORT
ARG ELASTICSEARCH_API_KEY
ARG REDIS_HOST
ARG REDIS_PORT
ARG REDIS_PASSWORD
ARG OLLAMA_ENDPOINT
ARG OLLAMA_EMBEDDING_MODEL

ENV DB_HOST=${DB_HOST}
ENV DB_PORT=${DB_PORT}
ENV DB_USER=${DB_USER}
ENV DB_PASSWD=${DB_PASSWD}
ENV JWT_SECRET=${JWT_SECRET}
ENV KAFKA_HOST=${KAFKA_HOST}
ENV KAFKA_PORT=${KAFKA_PORT}
ENV DOCUHELPER_FILE_ENDPOINT=${DOCUHELPER_FILE_ENDPOINT}
ENV OPENAI_API_KEY=${OPENAI_API_KEY}
ENV ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}
ENV ELASTICSEARCH_PORT=${ELASTICSEARCH_PORT}
ENV ELASTICSEARCH_API_KEY=${ELASTICSEARCH_API_KEY}
ENV REDIS_HOST=${REDIS_HOST}
ENV REDIS_PORT=${REDIS_PORT}
ENV REDIS_PASSWORD=${REDIS_PASSWORD}
ENV OLLAMA_ENDPOINT=${OLLAMA_ENDPOINT}
ENV OLLAMA_EMBEDDING_MODEL=${OLLAMA_EMBEDDING_MODEL}

COPY . /app

WORKDIR app

RUN chmod +x gradlew

RUN sh gradlew build --warning-mode all

ENTRYPOINT ["java", "-jar", "api-module/app/build/libs/app-0.0.1-SNAPSHOT.jar"]