apiVersion: apps/v1
kind: Deployment

metadata:
  name: docuhelper-api-deployment

spec:
  replicas: 3
  selector:
    matchLabels:
      app: docuhelper-api
  template:
    metadata:
      labels:
        app: docuhelper-api
    spec:
      containers:
        - name: docuhelper-api-container
          image: docker.bmserver.org/docuhelper-api:$IMAGE_TAG
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: docuhelper-configmap-prod
---

apiVersion: v1
kind: Service

metadata:
  name: docuhelper-api-service

spec:
  type: NodePort
  selector:
    app: docuhelper-api
  ports:
    - protocol: TCP
      targetPort: 8080    # pod 포트
      port: 8080          # 서비스 내부 포트
      nodePort: 30001      # 서비스 외부 포트
