rootProject.name = "docuhelper"
include(":api-module")
include(":api-module:app")
include(":api-module:gateway")
include(":common-module:docuhelper-file")
include(":common-module:core")
include(":common-module:redis")
include(":api-module:kafka")
include(":api-module:user-client")
include(":api-module:ai")
