server:
  port: ${PORT:8080}

spring:
  application:
    name: docuhelper-api
  r2dbc:
    url: r2dbc:pool:postgres://${DB_HOST:192.168.0.7}:${DB_PORT:5432}/${DB_SCHEMA:docuhelper} # schema ??? webflux? ???
    username: ${DB_USER:postgres}
    password: ${DB_PASSWD:password}
  security:
    jwt:
      secret: ${JWT_SECRET:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855}

graphql:
  packages: "org.bmserver.docuhelperapi"

logging:
  level:
    org.springframework.jdbc.core: DEBUG
    org.springframework.r2dbc: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG
