spring:
  application:
    name: docuhelper-api
  kafka:
    producer:
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


graphql:
  packages:
    - "org.bmserver.app"
    - "org.bmserver.core"
    - "org.bmserver.gateway"

