spring:
  application:
    name: redis
  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  data:
    redis:
      host: 192.168.0.7
      port: 6379
      password: passwd
